import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {AuthProvider} from "@/app/components/context/AuthProvider"
import {Toaster} from "sonner";
import SimpleNav from "@/components/SimpleNav"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// surround {children} w/ AuthProvider allows us to use AuthContext anywhere in the app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // change: use .className instead of .variable to prevent hydration errors
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <SimpleNav />
        <AuthProvider>{children}</AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
